import re


BYPASS_ENV_VAR = "AI_AGENT_BYPASS"
BYPASS_TTL_SECONDS = 120
DIFF_CONTEXT_LINES = 8
API_KEY_FALLBACK_FILE = ".api_key"
MAX_FILE_SIZE_BYTES = 150 * 1024
MAX_FILE_LINES = 2000
MAX_RETRY_ATTEMPTS = 3
MAX_FILES_TO_ANALYZE = 10
TEST_TIMEOUT_SECONDS = 30

ZERO_SHA_RE = re.compile(r"^0+$")
